# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build-lib:
    docker:
      - image: circleci/node:10-stretch

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run tests
          command: yarn test

  build-cli:
    docker:
      - image: node:latest

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache: &restore_cache
          keys:
          - v2-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run:
          name: Install dependencies
          command: yarn

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

      - run: ./bin/run --version

      - run: ./bin/run --help

      - run:
          name: Testing
          command: yarn test

      - run:
          name: Compile
          command: yarn pack

      - run:
          name: Speccy (single file)
          command: ./bin/run generate --api examples/single-file/api.ts -l yaml --generator openapi-3 -o output/ && ./node_modules/.bin/speccy lint output/api.yml

      - run:
          name: Speccy (multiple files)
          command: ./bin/run generate --api examples/multi-file/api.ts -l yaml --generator openapi-3 -o output/ && ./node_modules/.bin/speccy lint output/api.yml

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-lib
      - build-cli
